apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-extendproxy-v3
  namespace: castimaging-v3
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: castimaging-v3-local-storage
  local:
    path: "/home/jar/pv/console-v3-extendproxy"
  claimRef:
    namespace: castimaging-v3
    name: pvc-extendproxy-v3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubtest3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-extendproxy-v3
  namespace: castimaging-v3
  labels:
    console.service: extendproxy
spec:
  volumeName: pv-extendproxy-v3
  accessModes:
    - ReadWriteOnce
  storageClassName: castimaging-v3-local-storage
  resources:
    requests:
      storage: 5Gi